from matplotlib import pyplot as plt
import prices_data as pd
import datetime as dt

data_file = "../data/prices2013.dat"
dat = pd.load_prices(data_file)
data_days = pd.get_data_prevdays(dat, dt.datetime.strptime("2013-12-1", '%Y-%m-%d').date(), dt.timedelta(50))
feature_data1 = list()
feature_data2 = list()
feature_data3 = list()
feature_data4 = list()
feature_data5 = list()
feature_data6 = list()
feature_data7 = list()
feature_data8 = list()
feature_data9 = list()
feature_data10 = list()
for period in data_days:
    feature_data1.append(period["SMPEP2"])
    feature_data2.append(period["PeriodOfDay"])
    feature_data3.append(period["ForecastWindProduction"])
    feature_data4.append(period["SystemLoadEA"])
    feature_data5.append(period["SMPEA"])
    feature_data6.append(period["ORKTemperature"])
    feature_data7.append(period["ORKWindspeed"])
    feature_data8.append(period["CO2Intensity"])
    feature_data9.append(period["ActualWindProduction"])
    feature_data10.append(period["SystemLoadEP2"])

plt.plot(feature_data1)
plt.plot(feature_data2)
plt.xlabel("Cost")
plt.ylabel("Period of Day")
plt.show()

plt.plot(feature_data1)
plt.plot(feature_data3)
plt.xlabel("Cost")
plt.ylabel("ForeCasted wind production")
plt.show()

plt.plot(feature_data1)
plt.plot(feature_data4)
plt.xlabel("Cost")
plt.ylabel("SystemLoadEA")
plt.show()

plt.plot(feature_data1)
plt.plot(feature_data5)
plt.xlabel("Cost")
plt.ylabel("SMPEA")
plt.show()

plt.plot(feature_data1)
plt.plot(feature_data6)
plt.xlabel("Cost")
plt.ylabel("ORKTemperature")
plt.show()

plt.plot(feature_data1)
plt.plot(feature_data7)
plt.xlabel("Cost")
plt.ylabel("ORKWindspeed")
plt.show()

plt.plot(feature_data1)
plt.plot(feature_data8)
plt.xlabel("Cost")
plt.ylabel("CO2Intensity")
plt.show()

plt.plot(feature_data1)
plt.plot(feature_data9)
plt.xlabel("Cost")
plt.ylabel("ActualWindProduction")
plt.show()

plt.plot(feature_data1)
plt.plot(feature_data10)
plt.xlabel("Cost")
plt.ylabel("SystemLoadEP2")
plt.show()
